### ISSUE TITLE
Need DAI,ETH, USDC for reviewing and providing feedback for the project

### ISSUE THREAD

**Issue by kuldeep23907** [niftrr/blockchain-developer-bootcamp-final-project#1]
Hi Michael Gordon -- I am Kuldeep, one of the mentors helping in the grading. I am not able to contact with you on twitter so if possible, please send me the tokens at this address `0xFf10bE91e2717C896eD0Ce172C988432D0A0E660` so i can proceed with reviewing the project and grade it.

Thanks

**Comment by 0xMichaelGordon** [comment]
Hi Kuldeep, you should have the DAI, USD and WETH now in your wallet. Suggest you use the WETH to liquidate the Punk and then you'll have the NFT to play around with too. Thanks!

**Comment by kuldeep23907** [comment]
Thanks
